### 0. 대표적인 데이터분석용 라이브러리
- 넘파이(Numpy) : 넘파이 배열, 리스트 확장판
- 판다스(Pandas) : 테이블형태의 데이터 처리...대용량 데이터 빠른 속도 처리
- 맷플롯립(Matplotlib) : 파이썬의 시각화를 담당하는 라이브러리
- 외부모듈을 설치할 경우는 파이썬 파이프연산을 통해서 설치한다....아나콘다 powershell prompt에서 실행 (관리자 모드) 
- pip install numpy pandas matplotlib

In [3]:
# 모듈 로딩 import
# vector - 1차원 하나의 데이터를 가지고 있는 것.
# 행렬 - 행과 열을 가지고 있는 자료.
# list
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 0]
a + b # append의 의미

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [5]:
# 라이브러리 로딩
import numpy as np # 별칭
arr1 = np.array(a)
arr2 = np.array(b)
arr1 + arr2

array([ 7,  9, 11, 13,  5])

In [6]:
print(type(arr1))
print(type(a))

<class 'numpy.ndarray'>
<class 'list'>


In [9]:
print(len(a)) # 요소의 객수 읽어오는 함수

5


In [10]:
# 넙파이 배열의 크기. shape
arr1.shape # (x, y) -> x :행, y:열

(5,)

In [12]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
ar # 1차원 형태

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [13]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer = []
for i in data:
    answer.append(i*2)

# answer = [i*2 for i in data] -> list comprehension    
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [14]:
x = np.array(data)
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# 벡터화 연산
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [18]:
print(a+b)
a-b

[11 22 33]


array([ -9, -18, -27])

In [19]:
a == 2 # 비교연산자와 관계연산자의 결과는 True or False 

array([False,  True, False])

In [20]:
b > 10

array([False,  True,  True])

In [21]:
(a == 2) & (b > 10) # & :and 두 조건이 다 만족해야함

array([False,  True, False])

In [23]:
# 2차원 배열 : 행(가로, row)과 열(세로, column)
a = [[0, 1, 2], [3, 4, 5]]
a

[[0, 1, 2], [3, 4, 5]]

In [24]:
c = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
# 행의 갯수
len(a)

2

In [26]:
# np 행의 갯수
len(c)

2

In [27]:
# 열의 갯수
len(c[0])

3

In [28]:
c.shape

(2, 3)

In [31]:
# 3차원 배열 생성 2 x 3 x 4 (면, 행, 열)
d = np.array([[[1, 2, 3, 4], 
              [5, 6, 7, 8],
              [9, 10, 11, 12]], 
             [[11, 12, 13, 14],
             [15, 16, 17, 18],
             [19, 20, 21, 22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [32]:
# 면, 행, 열
print(len(d), len(d[0]), len(d[0][0]))

2 3 4


In [33]:
# 배열의 차원-ndim, 크기(속성) - shape (열의 크기도 알 수 있음)
d.shape

(2, 3, 4)

In [34]:
d.ndim

3

In [35]:
# 배열의 인덱싱
a = np.array([0, 1, 2, 3, 4])
a[2]

2

In [36]:
a[-1]

4

In [38]:
b = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3
b

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
# [조건식], [행, 열]
b[1, 0]

3

In [41]:
b[1, 1]

4

In [42]:
# 마지막행 마지막열
b[-1, -1]

5

In [43]:
# 슬라이싱(slicing)
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
# 첫번째행, [행, 열]
c[0, :] # c[0, 0:5]

array([1, 2, 3, 4])

In [48]:
# 두번째 열 전체
c[:, 1] 

array([2, 6])

In [49]:
# 두번째 행의 두번째 열부터 끝열까지
c[1, 1:]

array([6, 7, 8])

In [50]:
c[0:,0:2] # c[:2,:2]

array([[1, 2],
       [5, 6]])

In [51]:
# 펜싱 인덱싱
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])

a[idx] # True라는 건만 출력

array([0, 2, 4, 6, 8])

In [52]:
a % 2 # boolean 값

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [53]:
a % 2 == 0 # 비교연산자

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [54]:
# a[조건식] - 행열에서 조건식에 맞는 값을 불러옴
a[a%2 == 0]

array([0, 2, 4, 6, 8])

In [56]:
# 넘파이 자료형, type => dtype , 배열의 자료형을 읽어오는 속성
x = np.array([1, 2, 3])
print(x.dtype) # 요소의 자료형 32비트 정수
print(type(x))

int32
<class 'numpy.ndarray'>


In [58]:
x = np.array([1.0, 2.0, 3.0])
x.dtype # 요소의 자료형 64비트 실수
       # 기본적인 float는 64비트다. 32비트 없음

dtype('float64')

In [59]:
x = np.array([1, 2, 3.0]) # 눈에는 정수, 정수, 실수
x.dtype            # 실질적 저장은 실수, 실수, 실수

dtype('float64')

In [60]:
x # 실수, 동일한 타입의 데이터를 담는다.

array([1., 2., 3.])

In [67]:
# dtype 변경 'f' -> 실수, 'i' -> 정수
x = np.array([1, 2, 3], dtype = 'f')
x.dtype

dtype('float32')

In [64]:
# 'U' -> unsign int (부호 없는 정수)
x = np.array([1, 2, 3], dtype = 'U')
x.dtype # '<U1' : 유닛코드(문자표현) 형태로 가지고 있음.

dtype('<U1')

In [65]:
x # 문자열 취급을 한다.

array(['1', '2', '3'], dtype='<U1')

In [68]:
# inf 와 NaN
# inf -> 무한대라는 의미.
# NaN -> 정의할수 없는 숫자.
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0]) #경고

C:\anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.
C:\anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


array([  0.,  inf, -inf,  nan])

In [69]:
np.log(0) # 경고

C:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [70]:
# 배열 생성 명령 : 단순한 배열을 생성하는 명령어
# zeros, ones : 배열을 0으로 만들어라, 1로 만들어라
a = np.zeros(5)
b = np.ones(5)
print(a)
print(b)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [73]:
# 배열의 크기 : (행, 열) # 다차원 행렬을 받으려면 튜플타입으로 해야 함.
b = np.zeros((2, 3)) # 2행 3열 짜리에 0으로 채워라
b # 실수값을 잡힌다.

array([[0., 0., 0.],
       [0., 0., 0.]])

In [74]:
c = np.zeros((5, 2), dtype = 'i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [78]:
# 문자열 배열도 가능, 단 모든 원소열 크기가 같아야 한다.
d = np.zeros(5, dtype = 'U4') # U4 -> 16비트 init 코드 안쓰면 24비트 init 코드
d # 비어있는 공간에 문자열 할때 사용 # U1 -> 1글자 이하, U4 -> 4글자 이하
 # 글자면 3개 쓰고 잘라진다.

array(['', '', '', '', ''], dtype='<U4')

In [79]:
d[0] = 'abc'
d[1] = 'abcd'
d[2] = 'ABCDE'
d[3] = 'ABCDEFG'
d

array(['abc', 'abcd', 'ABCD', 'ABCD', ''], dtype='<U4')

In [83]:
e = np.ones((2, 3, 4), dtype = 'i')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [85]:
# ones_like -> 1과 같음의 의미, 배열의 크기를 명시하지 않고
# 다른 배열의 크기를 가져다 쓰고 싶을 때 사용
f = np.ones_like(b) # b (2x3 행렬)는 가져다 쓸 배열
f

array([[1., 1., 1.],
       [1., 1., 1.]])

In [87]:
# empty # 초기화하지 않고 사용할 수 있도록 하는 것.
g = np.empty([4, 3]) # 4x3 만들건데 알아서 초기화 해줘 -> 안의 값은 모름 
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [89]:
# arange : range의 Numpy 버젼
np.arange(10) # 0. .n-1 -> 0 ~ 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.arange(3, 21, 2) # 시작, 끝(포함하지 않는다), 증감

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [91]:
# linspace (- 선형구간)와 logspace (- 로그구간 )명령 
np.linspace(0, 100, 5) # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [92]:
np.logspace(0.1, 1, 10) # 0.1에서 1까지 10개 만듬.

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [95]:
# 전치연산 : 행과 열을 바꾸는 기능, T
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [96]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [98]:
# 배열의 크기 변형
# shape : 배열의 속성 확인
# reshape(행, 열)
a = np.arange(12) # 0 ~ 11
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [100]:
b = a.reshape(3, 4) # JAVA : 열의 값 적혀 잇으면 행 생략 가능
b                   # Python : 행의 값 젹혀 잇으면 열 생략 가능

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
a.reshape(3, -1) # -1은 자동이라는 의미

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [106]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [108]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [109]:
x.reshape(1, 5) # 1차원 배열과 의미가 다름, list더 들어감 
                # numpy는 다르게 취급 

array([[0, 1, 2, 3, 4]])

In [110]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [115]:
# 벡터(Vector)와 연산
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [116]:
a+b

array([5, 4, 5, 8])

In [117]:
a-b

array([-3,  0,  1,  0])

In [118]:
a*b

array([ 4,  4,  6, 16])

In [119]:
a/b

array([0.25, 1.  , 1.5 , 1.  ])

In [120]:
a == b

array([False,  True, False,  True])

In [121]:
a >= b

array([False,  True,  True,  True])

In [122]:
# all() : 모든 요소를 대상으로 비교하는 작업
np.all(a == b) # all 쓰기전은 각각의 요소끼리 비교

False

In [123]:
c = np.array([1, 2, 3, 4])
np.all(a == c)

True

In [125]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
x * 100 # 각요소에 100을 곱하는것

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [128]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [131]:
# 내장함수
# min, max, sum, mean, median, std, var, all, any

In [132]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [133]:
np.sum(x) # 모든 요소 합

10

In [134]:
# argmin 최솟값의 위치, argmax 최댓값의 위치
np.min(x)

1

In [135]:
np.argmin(x) # x배열에 최솟값의 위치를 알려달라

0

In [138]:
np.max(x)

4

In [139]:
np.argmax(x) # x배열에 최댓값의 위치를 알려달라

3

In [141]:
x.mean() # 평균
np.mean(x) # 둘다 가능, 하나로 통일

2.5

In [143]:
np.median(x) # 중앙값

2.5

In [144]:
np.all([True, True, False])

False

In [145]:
np.any([True, True, False])

True

In [148]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [149]:
np.sum(x)

10

In [151]:
np.sum(x[1,:]) #

7

In [152]:
x.sum(axis=0) # (0,0)+(1,0), (0,1)+(1,1) : 열의 합을 의미

array([4, 6])

In [153]:
x.sum(axis=1) # (0,0)+(0,1), (1,0)+(1,1) : 행의 합을 의미

array([3, 7])

In [158]:
a = np.array([[1, 2], [3, 4]], dtype= 'i')
b = np.array([[1, 2], [3, 4]], dtype= 'i')
print(a)
print(b)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [155]:
a + b

array([[2, 4],
       [6, 8]], dtype=int32)

In [156]:
a - b

array([[0, 0],
       [0, 0]], dtype=int32)

In [157]:
a * b # 요소의 곱

array([[ 1,  4],
       [ 9, 16]], dtype=int32)