In [1]:
# 필요 라이브러리 로딩
import numpy as np

In [2]:
def pprint(arr):
    print('type : {}'.format(type(arr)))
    print('shape : {}, dimension : {}, dtype : {}'.format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data : \n", arr)

In [3]:
arr = [1, 2, 3]
a = np.array(arr) # type : 객체 자료형 , dtype : 객체 안의 데이터 자료형

pprint(a)

type : <class 'numpy.ndarray'>
shape : (3,), dimension : 1, dtype : int32
Array's Data : 
 [1 2 3]


In [4]:
arr = [[1, 2, 3], [4, 5, 6]]
a = np.array(arr, dtype = float) #float라고 명시 해줌.

pprint(a)

type : <class 'numpy.ndarray'>
shape : (2, 3), dimension : 2, dtype : float64
Array's Data : 
 [[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
arr = [[[1, 2, 3], [4, 5, 6]], [[3, 2, 1], [4, 5, 6]]] # (2,3)이 2축
a = np.array(arr, dtype = float)
pprint(a)

type : <class 'numpy.ndarray'>
shape : (2, 2, 3), dimension : 3, dtype : float64
Array's Data : 
 [[[1. 2. 3.]
  [4. 5. 6.]]

 [[3. 2. 1.]
  [4. 5. 6.]]]


### numpy 배열 생성 및 초기화


In [6]:
a = np.zeros((3, 4)) # tuple 형태로 들어감
pprint(a)

type : <class 'numpy.ndarray'>
shape : (3, 4), dimension : 2, dtype : float64
Array's Data : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
a = np.ones((2, 3, 4), dtype = np.int16)
pprint(a)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4), dimension : 3, dtype : int16
Array's Data : 
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [8]:
# 단위행렬 ->  주대각선의 원소가 모두 1이며 나머지 원소는 모두 0인 정사각 행렬
a = np.identity(4, dtype = int)
b = np.eye(4, 4, k=1, dtype = int) # 주 대각선 원소를 k만큼 옮길 수 있음.
print(a)                        # 주 대각 원소에 0이 올 수 있음 but, 역행렬 존재X
print(b)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [9]:
# 기존 메모리 값 사용 -> 쓰레기 값이 나옴
a = np.empty((4, 2))
pprint(a)

type : <class 'numpy.ndarray'>
shape : (4, 2), dimension : 2, dtype : float64
Array's Data : 
 [[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 5.61258574e-321]
 [7.30399007e+173 1.17364597e-202]]


#### 난수 기반 배열 생성 - numpy.random 모듈
    normal(loc=0.0, scale = 1.0, size = None)
    정규 분포 확률 밀도에서 표본 추출
    loc : 정규 분포의 평균
    scale : 표준편차

In [10]:
# 난수 기반 배열 생성 # -> 많이 사용 ( 꼭 알아야 함 ).
mean = 0
std = 1
a = np.random.normal(mean, std, (2, 3))
pprint(a)

type : <class 'numpy.ndarray'>
shape : (2, 3), dimension : 2, dtype : float64
Array's Data : 
 [[-0.75052407  0.46159232 -1.15291532]
 [-0.45218334 -0.57743842 -0.50929874]]


In [11]:
# 임의의 값을 이용한 Numpy 배열 생성
data = np.random.randn(2,3)
data

array([[-0.23416002,  1.33568095, -2.31985362],
       [ 0.93084011, -2.01022232, -0.06714512]])

In [12]:
# 배열 차원의 크기
data.shape

(2, 3)

In [13]:
# 배열에 저장된 데이터의 형
data.dtype

dtype('float64')

### ndarray 생성

In [14]:
data = [[6, 7, 8, 0, 1]]
arr1 = np.array(data)
arr1

array([[6, 7, 8, 0, 1]])

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
# 배열의 차원 확인
arr1.ndim

2

In [17]:
arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

In [19]:
type(arr2) # 객체 자료형

numpy.ndarray

In [20]:
arr2.dtype # 객체안의 데이터의 자료형

dtype('int32')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
# 차원은 튜플타입으로 받아야 한다.
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
# 파이썬의 range() 와 같음
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
# dtype ,                  meta data -> 사용자가 원하는 타입으로 바꿀 수 있음.
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr2.dtype

dtype('int32')

In [28]:
arr1

array([1., 2., 3.])

In [29]:
arr2

array([1, 2, 3])

In [30]:
# astype() : 자료형을 캐스팅
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [31]:
float_arr = arr.astype(np.float64)
float_arr.dtype 

dtype('float64')

In [32]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [33]:
arr.astype(np.int32)
# float -> int 바꾸면 다른 언어는 round 하지만 numpy는 소수점을 버려지게 된다.

array([ 3, -1, -2,  0, 12, 10])

In [34]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [35]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

### Numpy 배열의 산술 연산

In [36]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr * arr # 각 요소들의 곱

array([[ 1,  4,  9],
       [16, 25, 36]])

In [38]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [39]:
1 / arr # 배열의 모든 스칼라 들이 나누어짐

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [40]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [41]:
arr2 = np.array([[0. , 4. , 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [42]:
arr2 > arr # union type

array([[False,  True, False],
       [ True, False,  True]])

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

### 인덱싱과 슬라이싱

In [45]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr[5]

5

In [47]:
# 파이썬 [start:end]
arr[5:8]

array([5, 6, 7])

In [48]:
arr[5:8] = 10 # 넘파이에서 슬라이싱은 뷰 객체(복사X, 원본 그대로)이다.

In [49]:
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [50]:
arr_slice = arr[5:8]
arr_slice

array([10, 10, 10])

In [51]:
arr_slice[1] = 12345 # 넘파이와 파이썬의 차이점
arr # 복사X 똑같은 값의 이름만 다른 원본값을 바꾼다.

array([    0,     1,     2,     3,     4,    10, 12345,    10,     8,
           9])

In [52]:
# [:] 전체요소
arr_slice[:] = 64 # 복사를 남발 하지 않음. 대용량 의 데이터 다루기 위해
arr # 계속 복사하면 성능과 메모리낭비 때문에 만약 복사 하고 싶으면 copy가 있음

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [53]:
# 다차원 배열의 색인
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr2d[2]

array([7, 8, 9])

In [55]:
arr2d[0][2] # 0번째 행에 2번째열

3

In [56]:
# 확장 가능 [행, 열] or [행의 start:end, 열의 start:end]
arr2d[0, 2]

3

In [57]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
# copy() - 원본 보존하고 사본으로 다룰 때.
old_value = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
arr3d[0] = old_value
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[1, 0] # 2번째 축에서 0번째 행과 모든 열을 가져와라.

array([7, 8, 9])

In [62]:
# 파이썬 일 때.
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [63]:
x[0] # 2번을 거쳐야 한다.

array([7, 8, 9])

In [64]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [65]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [66]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
arr2d[:2, 1: ] # 행은 0, 1 가져오고 열은 1열 부터 끝까지 가져오기

array([[2, 3],
       [5, 6]])

In [69]:
arr2d[1, :2] # 1번째 행, 0, 1번째 열

array([4, 5])

In [70]:
arr2d[:2, 2] # 0, 1번째 행 , 2번째 열

array([3, 6])

In [71]:
arr2d[:, :] # 전체다

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 불리언 배열을 이용하기

In [73]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [74]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [75]:
data

array([[-0.81451381,  2.07571401,  0.41728442,  1.88940716],
       [ 0.45108364,  1.66673926,  1.50344375,  0.1204481 ],
       [ 2.57899879,  1.13223445,  0.85498076, -0.54856772],
       [-1.89963126,  0.46080122, -0.30346977,  2.0873708 ],
       [-1.53925087, -1.66010285,  0.36674544, -0.94657541],
       [ 0.52424898, -0.15417757, -1.13101934, -0.40804821],
       [ 0.17677462, -1.7919948 ,  0.45092843, -0.07860016]])

In [76]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [77]:
# 'Bob'이랑 연관된 data row 추출
# [조건식], [범위], [행, 열], [행시:행마, 열시:열마]
data[names == 'Bob', 2:] # Bob 은 0, 3번째 인덱스 -> data의 0번째 3번째 추출
                        # 2: -> 2번째 열부터, 'BOb'이 행이 됨.                        

array([[ 0.41728442,  1.88940716],
       [-0.30346977,  2.0873708 ]])

In [78]:
data[names == 'Bob', 3]

array([1.88940716, 2.0873708 ])

In [79]:
# != or ~
# 'Bob'이 아닌 요소를 선택하는 작업
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [80]:
data[~(names == 'Bob')] # ~ == !=

array([[ 0.45108364,  1.66673926,  1.50344375,  0.1204481 ],
       [ 2.57899879,  1.13223445,  0.85498076, -0.54856772],
       [-1.53925087, -1.66010285,  0.36674544, -0.94657541],
       [ 0.52424898, -0.15417757, -1.13101934, -0.40804821],
       [ 0.17677462, -1.7919948 ,  0.45092843, -0.07860016]])

In [81]:
# 논리연산자 : &(and), |(or)
mask = (names == 'Bob') | (names == 'Will') # | -> 이거나
mask

array([ True, False,  True,  True,  True, False, False])

In [82]:
data[mask] #  참인 data만 추출

array([[-0.81451381,  2.07571401,  0.41728442,  1.88940716],
       [ 2.57899879,  1.13223445,  0.85498076, -0.54856772],
       [-1.89963126,  0.46080122, -0.30346977,  2.0873708 ],
       [-1.53925087, -1.66010285,  0.36674544, -0.94657541]])

In [83]:
data

array([[-0.81451381,  2.07571401,  0.41728442,  1.88940716],
       [ 0.45108364,  1.66673926,  1.50344375,  0.1204481 ],
       [ 2.57899879,  1.13223445,  0.85498076, -0.54856772],
       [-1.89963126,  0.46080122, -0.30346977,  2.0873708 ],
       [-1.53925087, -1.66010285,  0.36674544, -0.94657541],
       [ 0.52424898, -0.15417757, -1.13101934, -0.40804821],
       [ 0.17677462, -1.7919948 ,  0.45092843, -0.07860016]])

In [84]:
# data의 요소중에 음수 인것은 모두 0으로 변환
data[data < 0] = 0 # 데이터 크기만큼 추출
data

array([[0.        , 2.07571401, 0.41728442, 1.88940716],
       [0.45108364, 1.66673926, 1.50344375, 0.1204481 ],
       [2.57899879, 1.13223445, 0.85498076, 0.        ],
       [0.        , 0.46080122, 0.        , 2.0873708 ],
       [0.        , 0.        , 0.36674544, 0.        ],
       [0.52424898, 0.        , 0.        , 0.        ],
       [0.17677462, 0.        , 0.45092843, 0.        ]])

In [86]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.45108364, 1.66673926, 1.50344375, 0.1204481 ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.52424898, 0.        , 0.        , 0.        ],
       [0.17677462, 0.        , 0.45092843, 0.        ]])

### 팬시 색인 : 정수 배열을 사용한 색인(Fancy Indexing)

In [87]:
arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [88]:
arr[4]

array([4., 4., 4., 4.])

In [89]:
arr[[4, 3, 0, 6]] # 원하는 값으로 색인

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [90]:
arr[[-3, -5, -7]] # -로 인해 거꾸로 값을 가져옴 -3은 밑에서 3번째임.

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [91]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [92]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] # 1행 0열, 5행 3열, 7행 1열, 2행 2열 출력

array([ 4, 23, 29, 10])

In [93]:
# 각 1 5 7 2행의 0 3 1 2열 가져올려면?? 
#    1, 5, 7, 2행, : -> 행 다가져오고, 각 행의 0, 3, 1, 2열을 출력
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [94]:
# 전치행렬(행과 열의 크기를 바꾸는 행렬)
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [95]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [96]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [97]:
A

array([[1, 2],
       [3, 4]])

In [98]:
B

array([[5, 6],
       [7, 8]])

In [99]:
A+B

array([[ 6,  8],
       [10, 12]])

In [100]:
A*B

array([[ 5, 12],
       [21, 32]])

In [101]:
# 행렬의 곱
np.dot(A, B)

array([[19, 22],
       [43, 50]])

### 유니버셜 함수 : 배열의 각 원소를 빠르게 처리하는 함수
- ufunc 라고 불리기도 함

In [102]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [104]:
x = np.random.randn(8)
y = np.random.randn(8)

In [105]:
x

array([ 0.76035257,  1.11374872,  0.1046082 ,  0.24568092, -0.19352418,
        0.70450326,  1.47343279,  1.45811071])

In [106]:
y

array([ 1.16906752,  0.06475833,  0.03749493,  1.70854515, -1.4171979 ,
       -1.18840508,  2.620649  , -0.12637517])

In [107]:
np.maximum(x, y)

array([ 1.16906752,  1.11374872,  0.1046082 ,  1.70854515, -0.19352418,
        0.70450326,  2.620649  ,  1.45811071])

### 정렬

In [108]:
arr = np.random.randn(8)
arr

array([ 0.16746955, -0.19025848, -0.61006825,  0.67054561,  0.32318362,
        0.65387585,  1.3223509 , -2.03805677])

In [109]:
arr.sort()
arr

array([-2.03805677, -0.61006825, -0.19025848,  0.16746955,  0.32318362,
        0.65387585,  0.67054561,  1.3223509 ])

In [110]:
# np.unique() -> 중복을 없애는 함수
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [111]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [112]:
ints = np.array([3, 3, 3, 4, 4, 1, 1, 2, 2])
np.unique(ints)

array([1, 2, 3, 4])

In [113]:
sorted(set(names))

['Bob', 'Joe', 'Will']