In [1]:
# 표준 라이브러리 로딩
import numpy as np
import pandas as pd
# from pandas import Series, DataFrame

In [2]:
# Series : 1차원 배열, index + value
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj2 = pd.Series([4, 7, -5, 3], index = ['d', 'b', 'e', 'c'])
obj2

d    4
b    7
e   -5
c    3
dtype: int64

In [6]:
obj2['e']

-5

In [7]:
obj2['d'] = 6
obj2

d    6
b    7
e   -5
c    3
dtype: int64

In [8]:
obj2[['c', 'e', 'd']]

c    3
e   -5
d    6
dtype: int64

In [9]:
obj2[obj2 > 0] # 조건식이 참인것만 출력

d    6
b    7
c    3
dtype: int64

In [10]:
obj*2

0     8
1    14
2   -10
3     6
dtype: int64

In [11]:
'b' in obj2

True

In [12]:
'a' in obj2

False

In [13]:
# 파이썬의 사전을 이용하여 Series를 생성
# 사전에서 key가 Series의 index가 된다.
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [14]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index = states) # 주의 : sdata에 없는 키 값을 사용하면 결칙처리 됨.
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [15]:
# 결측값을 찾는 함수 : isnull() -> 결측값 입니까??, notnull()
pd.isnull(obj4) # obj4에 결측값이 있습니까??

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [16]:
pd.notnull(obj4) # obj4에 결측값이 없습니까??

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [17]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [18]:
# name 속성
obj4.name = 'population'
obj.index.name = 'state'
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [19]:
obj # 될 수 있으면 숫자 인덱스 사용X

state
0    4
1    7
2   -5
3    3
dtype: int64

In [20]:
# index 변경
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame
- 표형태의 자료구조
- 여러개의 컬럼이 존재하고, 각 컬럼은 서로 다른 값을 담을 수 있다.
- 2차원 배열

In [22]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop':[1.5, 1.7, 3.6, 2.4, 2.9, 3.7]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.7

In [23]:
# head(), tail() : 데이터프레임의 내용의 앞, 뒷단 5개의 row를 표시
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [24]:
frame.head(3) # 수치만큼 화면에 띄움, default는 5개

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [25]:
pd.DataFrame(data, columns = ['year', 'state', 'pop']) # 바꾸어서 볼 수 있음.

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.7

In [26]:
frame2 = pd.DataFrame(data, 
                      columns = ['year', 'state', 'pop', 'debt'], 
                     index = ['one', 'two', 'three', 'four', 'five', 'six'])
frame2 # 키 값이 없는건 결측 처리 됨.

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.7  NaN

In [27]:
frame2.columns # object type -> 문자열이라고 생각.

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [28]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [29]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [30]:
# [] 쓰기 싫을 때
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [31]:
# 특정 행은 위치나 loc속성
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [32]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.7  16.5

In [33]:
frame2['debt'] = np.arange(6.) # float 타입을 넣겠다는 의미
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.7   5.0

In [34]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])
frame2['debt'] = val # 'two', 'four', 'five' 외에는 결측처리 됨.
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.7   NaN

In [35]:
# del 예약어를 통해 컬럼을 삭제
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.7   NaN    False

In [36]:
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.7   NaN

In [37]:
# 중첩된 사전을 이용한 데이터프레임 생성
pop = {'Navada':{2001:2.4, 2002:2.9},
      'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}
frame3 = pd.DataFrame(pop)
frame3

Navada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [38]:
frame3.T

2000  2001  2002
Navada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [41]:
pd.DataFrame(pop, index = [2001, 2002, 2003])

Navada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [42]:
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Navada':frame3['Navada'][:2]}
pd.DataFrame(pdata)

Ohio  Navada
2000   1.5     NaN
2001   1.7     2.4

In [43]:
frame3

Navada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [44]:
# name 속성
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Navada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [45]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [46]:
frame2.values # 안의 데이터가 다르기 때문에 dtype이 뜬다.

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.7, nan]], dtype=object)

### DataFrame의 인덱스

In [47]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int64

In [48]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [49]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [50]:
index[1:]

Index(['b', 'c'], dtype='object')

In [51]:
# 색인(index) 객체는 변경이 불가능하다. -> 자료의 안전성을 보장하기 위해
index[1]='d'

TypeError: Index does not support mutable operations

In [52]:
# 재색인(reindex) : 객체를 새로 생성
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [53]:
obj2 = obj.reindex(['a', 'b', 'c', 'd','e']) # 'e'는 obj의 값X -> 결측치 처리
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [54]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [57]:
obj3.reindex(range(6)) 

0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object

In [58]:
# 누락된 값을 직전의 값으로 채워주는 역활
obj3.reindex(range(6), method='ffill')# 결측치 값을 이전값으로 채워진다

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [59]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index = ['a', 'c', 'd'],
                    columns = ['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [61]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [62]:
states = ['Texas', 'Utah', "California"] # 컬럼도 reindex 가능.
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [63]:
obj = pd.Series(np.arange(5.), index= ['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [64]:
new_obj = obj.drop('c') # 특정 행이 삭제
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [65]:
obj.drop(['d', 'c']) # 여러행도 삭제 가능

a    0.0
b    1.0
e    4.0
dtype: float64

In [66]:
obj # drop method로 원본 삭제X

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [67]:
obj.drop(['d', 'c'], inplace= True) # inplace : 원본도 삭제하라

In [68]:
obj

a    0.0
b    1.0
e    4.0
dtype: float64

In [69]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index = ['Ohio', 'Colorado', 'Utah', "New york"],
                   columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New york   12   13     14    15

In [70]:
data.drop(['Ohio', 'Colorado']) # 인덱스 삭제

one  two  three  four
Utah        8    9     10    11
New york   12   13     14    15

In [71]:
# 컬럼 삭제 할 때는 축(axis)도 같이 넘겨줘야 함.
data.drop('two', axis=1) # axis='columns' 이렇게도 사용가능 

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New york   12     14    15

In [72]:
data.drop(['two', 'four'], axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New york   12     14

In [73]:
data # 원본 삭제 안됨. 원본 삭제 할려면 inplace = True라고 넣어줘야함.

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New york   12   13     14    15

In [75]:
obj = pd.Series(np.arange(4.), index = ['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [76]:
obj[1]

1.0

In [77]:
obj['b']

1.0

In [78]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [79]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [80]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [81]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [82]:
obj['b':'c'] # 라벨로 슬라이싱은 마지막 라벨까지 출력이 됨

b    1.0
c    2.0
dtype: float64

In [83]:
obj[1:2] # 하나만 출력됨. 값으로 슬라이싱은 마지막 값은 출력X

b    1.0
dtype: float64

In [84]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [85]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New york   12   13     14    15

In [86]:
data['two']

Ohio         1
Colorado     5
Utah         9
New york    13
Name: two, dtype: int32

In [87]:
data[['three', 'one']] # 하나이상 출력을 원할 때는 팩터화 시켜야 됨.

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New york     14   12

In [88]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [89]:
data[data['three'] > 5] # 주의 : 조건만 말하는 거고 출력은 모두 다.

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New york   12   13     14    15

In [90]:
data < 5 # boolean 값으로 출력 -> True , False

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New york  False  False  False  False

In [91]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New york   12   13     14    15

In [92]:
# loc, iloc 속성
# loc : 축 이름을 선택 할 때
# iloc : 정수 인덱스를 선택 할 때

In [93]:
# [행, 열]
data.loc['Colorado',['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [94]:
data.iloc[1, [1, 2]]

two      5
three    6
Name: Colorado, dtype: int32

In [95]:
data.iloc[2] # 두번째 row 즉 , Utah가 출력됨

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [96]:
 data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [97]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [98]:
data.iloc[:,:3][data.three > 5] # data['three'] 이렇게 사용해도 됨. 다이렉트로 하면 '' 사용X

one  two  three
Colorado    0    5      6
Utah        8    9     10
New york   12   13     14

In [99]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [100]:
ser[-1] # 배열의 마지막 값 -> 키 에러 -> 정수 값 인덱싱 할때는 모호 할 수 있다. -> iloc 사용

KeyError: -1

In [101]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1] # 인덱싱으로 부여하면 가능하다. -> 앞에껀 index X -> 일반화 모호함, iloc 사용

2.0

In [102]:
ser[:1] # : 달면 실행 가능

0    0.0
dtype: float64

In [103]:
# 라벨 색인 -> 되지만 원하는 값이 나오지 X
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [104]:
# 정수 색인 -> 즉 이것말고는 일반성이 떨어지니 iloc 사용하는 것을 추천.
ser.iloc[:1]

0    0.0
dtype: float64

### 산술 연산

In [109]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a', 'c', 'e', 'f', 'g'])

In [110]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [111]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [112]:
# 판다스는 색인을 기준으로 연산 ( 맞는 색인 끼리 연산 )
s1 + s2 # 짝이 맞지 않은 색인의 연산은 결측값이 됨.

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [120]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), 
                  columns = list('bcd'), 
                  index = ['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                  columns = list('bde'), 
                  index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [121]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [122]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [123]:
df1 + df2 

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [124]:
df1.add(df2, fill_value = 0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [117]:
# 공통된 값이 없으면 아무것도 나타나지 않는다.
df1 = pd.DataFrame({'A':[1, 2]})
df2 = pd.DataFrame({'B':[3, 4]})

In [118]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [119]:
df1.add(df2, fill_value = 0) # 0이랑 더해져서 자기자신의 값이 나옴

A    B
0  1.0  3.0
1  2.0  4.0

In [125]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [126]:
arr[0]

array([0., 1., 2., 3.])

In [127]:
arr - arr[0] # arr[0]이 arr 각 행이랑 연산이됨.

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [128]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                  columns = list('bde'), 
                  index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]

In [129]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [130]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [131]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [132]:
series2 = pd.Series(range(3), index=['b','e','f'])
series2

b    0
e    1
f    2
dtype: int64

In [133]:
# reindex 처리가 됨.
frame + series2 

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [137]:
frame = pd.DataFrame(np.random.randn(4,3), 
                  columns = list('bde'), 
                  index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.629778  1.093418 -0.456433
Ohio   -0.037614 -1.414706 -0.330488
Texas  -0.911869  1.128069  0.089676
Oregon -1.432395  1.035971 -0.141059

In [138]:
np.abs(frame)

b         d         e
Utah    0.629778  1.093418  0.456433
Ohio    0.037614  1.414706  0.330488
Texas   0.911869  1.128069  0.089676
Oregon  1.432395  1.035971  0.141059

In [139]:
# frame 데이터에서 각 로우마다 최대값에서 최소값을 뺀 결과값을 추출하려면
# apply() : 특정 함수를 이용하여 반복적인 계산을 수행할 때 사용된다.
# lambda 입력 : 출력
f = lambda x : x.max() - x.min()
frame.apply(f)

b    1.394781
d    2.542776
e    0.546109
dtype: float64

In [141]:
frame.apply(f, axis = 'columns')

Utah      1.723196
Ohio      1.377092
Texas     2.039938
Oregon    2.468366
dtype: float64

In [143]:
frame

b         d         e
Utah   -0.629778  1.093418 -0.456433
Ohio   -0.037614 -1.414706 -0.330488
Texas  -0.911869  1.128069  0.089676
Oregon -1.432395  1.035971 -0.141059

In [144]:
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min', 'max'])

frame.apply(f) 

b         d         e
min -1.432395 -1.414706 -0.456433
max -0.037614  1.128069  0.089676

In [145]:
frame

b         d         e
Utah   -0.629778  1.093418 -0.456433
Ohio   -0.037614 -1.414706 -0.330488
Texas  -0.911869  1.128069  0.089676
Oregon -1.432395  1.035971 -0.141059

In [146]:
fmt = lambda x : '%.2f' % x # 문자열 format 형식
frame.applymap(fmt) # 문자열 할 때

b      d      e
Utah    -0.63   1.09  -0.46
Ohio    -0.04  -1.41  -0.33
Texas   -0.91   1.13   0.09
Oregon  -1.43   1.04  -0.14

In [147]:
frame['e'].map(fmt) # float이 아닌 object 타입

Utah      -0.46
Ohio      -0.33
Texas      0.09
Oregon    -0.14
Name: e, dtype: object

### GroupBy 객체

In [2]:
df = pd.DataFrame({'key':['a', 'b', 'c']*4, 
                  'value':np.arange(12.)})
df

key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [5]:
# 'key'별로 평균을 계산하여 추출하시오.
tmp = df.groupby('key').value
tmp

In [6]:
tmp.mean() # 집계함수

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [7]:
# map - 범주형 데이터, 시리즈만 가능
# apply - 다양한 데이터

In [8]:
# lambda 입력 : 출력
# trnasform : 값을 반복해서 변경하고싶을때 사용
tmp.transform(lambda x : x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [9]:
tmp.transform('mean') # 내장함수들을 문자열로 담아도 같은 결과.

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [10]:
# 정규화 (숫자를 정규화 할때 많이 사용)
def normalize(x):
    return (x - x.mean()) / x.std()

In [11]:
tmp.transform(normalize) # 내장 함수 이외에는 문자열로 사용X

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [12]:
tmp.apply(normalize) # transform과 같은 결과

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64