In [1]:
# count : 데이터 개수
# 평균 : mean, average
# 분산 : var, variance
# 표준편차 : std, standart dviation
# 최대값 : maximum
# 최소값 : minimum
# 중앙값 : median
# 사분위수 : quartile

In [2]:
import numpy as np
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 5, 2, 
              15, 8, 2, 5, 4, 15, -1, 4, -7, -24,
             7, 9, -6, 23, -13])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   5,   2,  15,   8,   2,
         5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [3]:
len(x)

25

In [4]:
np.mean(x)

5.0

In [5]:
np.var(x)

118.88

In [6]:
np.std(x)

10.903210536351208

In [7]:
np.max(x)

23

In [8]:
np.min(x)

-24

In [9]:
np.median(x)

5.0

In [10]:
#백분위수(percentile) : 파이썬은 백분위수를 사용
np.percentile(x, 0) # 최솟값

-24.0

In [11]:
np.percentile(x, 100) #최댓값

23.0

In [12]:
np.percentile(x, 25) #1사분위수

0.0

In [13]:
np.percentile(x, 50) # 2사분위수

5.0

In [14]:
np.percentile(x, 75) # 3사분위수

10.0

In [15]:
np.percentile(x, 100) # 4사분위수

23.0

In [16]:
# 난수 발생
# rand() : 0과 1사이의 난수를 발생시키는 함수
np.random.rand(5)

array([0.76410721, 0.27291281, 0.89658011, 0.34051561, 0.15953823])

In [18]:
np.random.rand(10)

array([0.50525947, 0.71576368, 0.77741118, 0.4216492 , 0.53144416,
       0.57921315, 0.3953414 , 0.29819142, 0.06051869, 0.75775677])

In [19]:
np.random.rand(10)

array([0.24996867, 0.2914858 , 0.1687348 , 0.9742114 , 0.01827499,
       0.72945824, 0.65313713, 0.84730097, 0.43048871, 0.07053923])

In [20]:
# shuffle() : 데이터를 섞는다.
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.random.shuffle(x) # x의 값을 무작위로 섞어라.
x

array([3, 2, 4, 0, 9, 5, 7, 1, 6, 8])

In [26]:
np.random.choice(5, 5) # 0~4사이 숫자를 5개 만들어나라

array([4, 3, 1, 1, 4])

In [29]:
np.random.choice(5, 5, replace=False) # 같은 숫자는 안 나오게끔 , True하면 중복가능

array([4, 1, 0, 2, 3])

In [31]:
np.random.choice(5, 10, p = [0.1, 0, 0.3, 0.6, 0]) # p(percent)-> 선택 될 확률

array([3, 3, 0, 3, 2, 3, 2, 2, 3, 2], dtype=int64)

In [32]:
# rand 0 부터 1사이의 균일 부포에 해당하는 난수
# randn : 표준 정규 분포를 이용해서 난수 발생
# randint : 균일 분포할 때 난수가 정수이다.

In [33]:
np.random.rand(10)

array([0.1957197 , 0.21455279, 0.52251831, 0.47855852, 0.48127621,
       0.91559035, 0.02034475, 0.97268222, 0.35586501, 0.92129893])

In [34]:
np.random.rand(3, 5) # (행, 열)-> 차원, 3행 5열 크기로 난수를 발생

array([[0.40220767, 0.09950558, 0.81975305, 0.87121594, 0.60707348],
       [0.83204643, 0.60247698, 0.90816365, 0.10604824, 0.70429237],
       [0.97037824, 0.93937128, 0.83435868, 0.22743575, 0.23708347]])

In [35]:
np.random.randn(10)

array([ 0.45615897,  0.79770077, -0.16740019, -1.11233415,  1.06501275,
        0.43013609, -0.45644418, -0.02876406,  0.3001224 ,  0.24117104])

In [36]:
np.random.randn(3, 5)

array([[-0.96575599, -0.38958762, -0.37130806, -0.79135382,  0.00597896],
       [-0.47545705,  1.0776151 ,  1.58451081,  0.39041183,  0.23845705],
       [-0.57253882, -0.74815287,  0.48407518,  0.86625935,  0.96748371]])

In [38]:
# randint(최솟값, 최댓값, 사이즈) - 정규분포를 따른 정수
np.random.randint(10, size=10) # 0 ~ 9, size = 10

array([4, 7, 9, 4, 1, 6, 0, 4, 1, 6])

In [39]:
np.random.randint(10, 20, size=10) # 최소 10 최대 20 size 10

array([13, 11, 12, 14, 14, 16, 13, 10, 12, 19])

In [40]:
np.random.randint(10, 20, size=(3, 5)) # 최소 10 최대 20 size (행, 열)

array([[18, 18, 19, 10, 15],
       [16, 13, 19, 10, 14],
       [16, 15, 17, 11, 10]])

In [ ]:
# up % down game